### PR TITLE
place holder commit so I can commit and create pull request, as all previous…

### PR DESCRIPTION
**Pull request by lav-patel**
… commits are directly made to master

### CODE REVIEW

**Comment by lav-patel** [comment]
Hi Garrett,
Do you need this function `handle_file_list`? https://github.com/kumc-bmi/REDCap-ADCEnglishSpanish/blob/5bfb0bc3935f77db0851a75fc77ef40bcac485fb/combine_eng_esp.py#L45

**Comment by lav-patel** [comment]
You may want to add License terms like https://github.com/kumc-bmi/heron/blob/master/heron_load/create_concept_shortcuts.sql#L3

**Comment by lav-patel** [comment]
I could not find Automated Feature Tests.

**Comment by ghost** [comment]
> Hi Garrett,
> Do you need this function `handle_file_list`?
> 
> [REDCap-ADCEnglishSpanish/combine_eng_esp.py](https://github.com/kumc-bmi/REDCap-ADCEnglishSpanish/blob/5bfb0bc3935f77db0851a75fc77ef40bcac485fb/combine_eng_esp.py#L45)
> 
> Line 45 in [5bfb0bc](/kumc-bmi/REDCap-ADCEnglishSpanish/commit/5bfb0bc3935f77db0851a75fc77ef40bcac485fb)
> 
>  def handle_file_list(comb_file_list, export_dir):

Removed in [d592110] Good catch!

**Comment by ghost** [comment]
> You may want to add License terms like https://github.com/kumc-bmi/heron/blob/master/heron_load/create_concept_shortcuts.sql#L3

Added in [d592110]. Thanks!

**Pull request merged**
